### ISSUE TITLE
Why forwardSignalWhileActive:(RACSignal *)signal subscribes only on the next and error, but not completed?

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveViewModel#38]

**Comment by jspahrsummers** [comment]
This [isn't true](https://github.com/ReactiveCocoa/ReactiveViewModel/blob/822c734745c98756cc72ffb06881fbebe600be7e/ReactiveViewModel/RVMViewModel.m#L112-L114), so can you please describe what problem you're actually encountering in detail?

**Comment by larryonoff** [comment]
I'm not an expert in ReactiveCocoa, so I'm just assuming.
According to [this line of code](https://github.com/ReactiveCocoa/ReactiveViewModel/blob/822c734745c98756cc72ffb06881fbebe600be7e/ReactiveViewModel/RVMViewModel.m#L98) there is `subscribeNext:error:` signal to enclose is subscribed only on next and error. So if signal to enclose sends completed it isn't forwarded from `forwardSignalWhileActive:`.

Let me explain my goal in detail.
I have a signal which should be unsubscribed from when model isn't active and when the model is active subscribed on the signal again. And this signal should be command signal. So I created the signal (let's call it `signalToEnclose`), enclosed it into `forwardSignalWhileActive:` signal and made it a command signal then. As result when `signalToEnclose` sends completed, the command says that it's still executing, but it shouldn't.

PS. I've solved my issue in another way, but I'm still interested in understanding of `forwardSignalWhileActive:` behavior.

Thank you.

**Comment by jspahrsummers** [comment]
`forwardSignalWhileActive:` doesn't care if the _provided_ signal completes because [part of its contract](https://github.com/ReactiveCocoa/ReactiveViewModel/blob/822c734745c98756cc72ffb06881fbebe600be7e/ReactiveViewModel/RVMViewModel.h#L39-L40) is that it may re-subscribe to that signal any number of times.

If it actually forwarded completion events, it wouldn't be able to resubscribe, because the signal would be done forever.
